name: dba_mobile
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  auto_route: ^7.7.0
  
  
  flutter:
    sdk: flutter
  flutter_hooks: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  nb_utils: ^6.0.0
  get: ^4.6.5
  cached_network_image: ^3.2.1
  google_fonts: ^5.1.0
  get_it: ^7.6.0
  change_app_package_name: ^1.1.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  flutter_overlay_loader: ^2.0.0
  cloud_firestore: ^4.8.2
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.3
  auto_route_generator: ^7.2.0
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: "^0.13.1"
  freezed_annotation: ^2.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  #line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    #flare_flutter: true
    #rive: true
    

  assets:
    enabled: true